#!/bin/sh

args=''

for i in $@; do
    if echo $i | grep -q '.prec$'; then
        (cpp $i | grep -v '^# ' ) > $i.tmp &&
        (./prec_internal $i.tmp; ) > $i.tmp.c &&
        (cpp $i.tmp.c | grep -v '^# ' ) > $i.c &&
        rm $i.tmp && rm $i.tmp.c
        args=$args" "$i.c
    elif echo $i | grep -q '.preh$'; then
        (cpp $i | grep -v '^# ' ) > $i.tmp &&
        (./prec_internal $i.tmp; ) > $i.tmp.h &&
        (cpp $i.tmp.h | grep -v '^# ' ) > $i.h &&
        rm $i.tmp && rm $i.tmp.h
        args=$args" "$i.h
    else 
        args=$args" "$i
    fi
done

cc $args
